sudo: required
services:
  - docker

before_install:
  - docker build -t ais777/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ais777/react-test npm test -- --coverage

after_success:
  - docker build -t ais777/multi-client ./client
  - docker build -t ais777/multi-nginx ./nginx
  - docker build -t ais777/multi-server ./server
  - docker build -t ais777/multi-worker ./worker
  
