dist: focal
language: generic
sudo: required
services:
  - docker

before_install:
  - gem uninstall nokogiri -aIx || true
  - bundle config set force_ruby_platform true
  - docker build -t ais777/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ais777/react-test npm test

after_success:
  - docker build -t ais777/multi-client ./client
  - docker build -t ais777/multi-nginx ./nginx
  - docker build -t ais777/multi-server ./server
  - docker build -t ais777/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ais777/multi-client
  - docker push ais777/multi-nginx
  - docker push ais777/multi-server
  - docker push ais777/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-047719613436'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY