version: "3"
services:
  client:
    image: "ais777/multi-client"
    mem_limit: 128m
    hostname: client
  server:
    image: "ais777/multi-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "ais777/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    image: "ais777/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
  redis:
    iamge: "redis:latest"
    hostname: redis
    mem_limmit: 64m